#!/usr/bin/env bash
# Copyright 2012-2025 The Wazo Authors  (see the AUTHORS file)
# SPDX-License-Identifier: GPL-3.0-or-later

case $1 in
    config)
        cat <<'EOM'
graph_category xivo
graph_title XIVO ASTERISK file descriptors
graph_vlabel File descriptors count
asteriskfiledesc.label Nb of Asterisk file descriptors
asteriskfiledesc.draw AREA
EOM
        exit 0;;
esac

echo -n "asteriskfiledesc.value "; ls -d /proc/$(pidof asterisk)/fd/* 2>/dev/null | wc -l
exit 0
